# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PathFinderDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PathfinderDialog(object):
    def setupUi(self, PathfinderDialog):
        PathfinderDialog.setObjectName("PathfinderDialog")
        PathfinderDialog.resize(957, 809)
        self.gridLayout_2 = QtWidgets.QGridLayout(PathfinderDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.UofaMap = PlotWidget(PathfinderDialog)
        self.UofaMap.setObjectName("UofaMap")
        self.gridLayout_2.addWidget(self.UofaMap, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 1, 1, 1)

        self.retranslateUi(PathfinderDialog)
        QtCore.QMetaObject.connectSlotsByName(PathfinderDialog)

    def retranslateUi(self, PathfinderDialog):
        _translate = QtCore.QCoreApplication.translate
        PathfinderDialog.setWindowTitle(_translate("PathfinderDialog", "Dialog"))
from pyqtgraph import PlotWidget
